"""Initial migration

Revision ID: ab9ce35df261
Revises: e0b7248ef89a
Create Date: 2024-10-24 12:01:52.820719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9ce35df261'
down_revision = 'e0b7248ef89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizzas')
    op.drop_table('restaurant_pizzas')
    op.drop_table('restaurants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_pizzas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=False),
    sa.Column('pizza_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizzas.id'], name='fk_restaurant_pizzas_pizza_id_pizzas'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='fk_restaurant_pizzas_restaurant_id_restaurants'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pizzas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('ingredients', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
